### ISSUE TITLE
Matrix 6.8.0 spd

### ISSUE THREAD

**Issue by FallenCrystal** [opZywl/FDPClient-legacy#100]
matrix is upd

**Comment by DinoFengz** [comment]
any test server?

**Comment by FallenCrystal** [comment]
> any test server?

not. i think so
im not sure anticheat.ir is upd matrix

**Comment by DinoFengz** [comment]
gimme whitelist anticheat.ir

**Comment by contionability** [comment]
> matrix is upd

6.6.1 works through the way bruh
never got patched, Matrix Moment
