### ISSUE TITLE
[Bug] 打开即崩溃

### ISSUE THREAD

**Issue by LittleSadSheep** [opZywl/FDPClient-legacy#117]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
FDP打开出现加载页面后进度条读完就崩溃

**Crash Report**
If your game crashed, please paste your crash report below.
[错误报告-2022-6-15_14.39.31.zip](https://github.com/UnlegitMC/FDPClient/files/8906558/-2022-6-15_14.39.31.zip)

**System Information**
 - OS: [e.g. Windows 11]
 - Minecraft Version: [1.8.9]
 - Forge Version: [11.15.1.2318]
 - FDPClient Version: [4.3.0]

**Other Installed Mods**
没有

**Additional info**
用的PCL2启动器

**Comment by contionability** [comment]
https://github.com/UnlegitMC/FuckPCL
https://github.com/UnlegitMC/FDPClient/commit/f51e9829b6d92f7de4ff57f4bf8db108d1be9c8a

**Comment by HowardZHY** [comment]
remove this useless thing since liuli left
