### ISSUE TITLE
[Bug] <Fix GL Error in Ubuntu(Crashes every render)>

### ISSUE THREAD

**Issue by ProSteve12301** [opZywl/FDPClient-legacy#14]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<Its crashing every render.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Start UbuntuOS
2. Run Minecraft
3. Play SinglePlayer or MultiPlayer
4. Crashes.

**Expected behavior**
<When its render it freeze and crash.>

**Screenshots/Video**
Not available,because i using VNC Viewer and the screenshot is blank.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
Java Exit Code -8
```

**System Information**
 - OS: Ubuntu 20.00
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: 3.1.1

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Optifine 1.8.9

**Additional info**
<I just transfer to Ubuntu to expect a perfect cheating but its crashing(i using mobile and use terminal emulator to install UbuntuOS.>

**Comment by ProSteve12301** [comment]
Also using Minecraft Launcher in FlatPak App Packaging.And using Pojav Like GL Library.

**Comment by contionability** [comment]
may caused by Optifine
if GLError 1281 or 1282, turn off FastRender

**Comment by ProSteve12301** [comment]
> may caused by Optifine if GLError 1281 or 1282, turn off FastRender

I disable it and it crash every 30 seconds.I luck i have the backup of FDP 2.1.2,its working.

**Comment by ProSteve12301** [comment]
Also same problem in PojavLauncher,even MCinabox Launcher.

**Comment by ProSteve12301** [comment]
UwU the FDP Original Github Hacked:(
[FDP Client Hacked](https://github.com/Dimples-1337/FDPClient) Github.
