### ISSUE TITLE
[Suggestion] <Add Optimized version of FDP Client every release:)>

### ISSUE THREAD

**Issue by ProSteve12301** [opZywl/FDPClient-legacy#17]
Can FDP Team remove Visual/Graphical Design in FDP for different launcher like _PojavLauncher and MCinabox_ and suggestion to change **HUD** from FDP 2.1.2 because its no problem.

**Comment by ProSteve12301** [comment]
Also FDP 2.1.2 Visual is so good that no exits or crash happens.I used it but its no bypass at all i want to play latest of it but render exits prevent me to play.

**Comment by HowardZHY** [comment]
A vanilla style ui, like WURST, won't cause crashes.

**Comment by ProSteve12301** [comment]
> A vanilla style ui, like WURST, won't cause crashes.

Yeah like FDP 2.1.2,its optimized and actually its bypass BlocksMC new verus airlines and Minebox puppy WatchDog still killaura reach and infinite scaffold and hypixel disabler for airlines.

**Comment by ghost** [comment]
Stop using FDPClient, start using LiquidBounce with scripts.

**Comment by ProSteve12301** [comment]
Thanks for respond but i learn to code and i do it by myself.

Wish Fixed.
