### ISSUE TITLE
[Bug] <新版本疾跑跳跃过远导致反作弊拉回>

### ISSUE THREAD

**Issue by MatrixU5er** [opZywl/FDPClient-legacy#170]
在Main (idk) 版本上 ，疾跑不开任何模块跳的太远，Matrix NCP AAC Vulcan等反作弊都拉回.请尽快修复这个bug已给用户更好的体验。

**Comment by contionability** [comment]
Fixed
下载新版本覆盖原有配置就行了
or .sprint JumpDirection
(Overwrited: .sprint JumpDirections)
