### ISSUE TITLE
key blind

### ISSUE THREAD

**Issue by ra1n08** [opZywl/FDPClient-legacy#177]
how i can blind custom key for modules ?
i want to bind edge button

**Comment by gatooooooo** [comment]
.bind  <module> <button_id>
example
.bind aimbot shift

**Comment by ra1n08** [comment]
> .bind <button_id> example .bind aimbot shift

i want bind key in config default.json and i see key bind is numbers

**Comment by ghost** [comment]
Stop using FDPClient, start using LiquidBounce with scripts.

**Comment by DinoFengz** [comment]
close this
