### ISSUE TITLE
[Suggestion] Remove FDPPROTECT wtf is that 

### ISSUE THREAD

**Issue by lliZEDMASTERill** [opZywl/FDPClient-legacy#21]
Open Source Client With a Gaurd? wtf

**Comment by crowwd** [comment]
🐀

**Comment by ProSteve12301** [comment]
> Open Source Client With a Gaurd? wtf

LoL the FDPProtect used to be prevent to steal or skid module codes in .jar file.

**Comment by contionability** [comment]
> Open Source Client With a Gaurd? wtf

some kids stole our codes and pretended that they were coded by them

**Comment by contionability** [comment]
actually you can skid from our client but you need to mention that the code is from FDPClient

**Comment by crowwd** [comment]
> > Open Source Client With a Gaurd? wtf
> 
> LoL the FDPProtect used to be prevent to steal or skid module codes in .jar file.

why was it open source in the first place then

**Comment by choneas** [comment]
If this Issue has closed, please close this Issue.(WTF)
