### ISSUE TITLE
[Suggestion] <Can you continue EZ4H Project>

### ISSUE THREAD

**Issue by ProSteve12301** [opZywl/FDPClient-legacy#22]
[EZ4H Link](https://github.com/UnlegitMC/EZ4H)

Can you continue developing this project because i bored hacking on JartexNetwork.I wanna try to cheat in MCPE Servers.
(i said that you can develop this project sided time only).

And Optimized your FDP Client too to not enough crashes and Java exits.

**Comment by contionability** [comment]
EZ4H Project was led by Liuli
but liuli has quitted so it was archive, infinitely

**Comment by HowardZHY** [comment]
EZ4H is legacy now.

**Comment by ghost** [comment]
Stop using FDPClient, start using LiquidBounce with scripts.

**Comment by ProSteve12301** [comment]
Oh i continuing this because its working on MineplexPE(Because i update protocols and raknet native) but not with HiveMC(cuz need resources pack).

BTW thanks for respond:)

**Comment by ProSteve12301** [comment]
Byyyyy
