### ISSUE TITLE
[Bug] <Can you fix PojavLauncher Crash???>

### ISSUE THREAD

**Issue by ProSteve12301** [opZywl/FDPClient-legacy#227]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<Fix Latest FDP Crashing.I can't even fix GL4ES bug of PojavLauncher:(.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Play Minecraft.
2. Join SinglePlayer or Multiplayer.
3. Play a little bit.
4. and Crash.

**Expected behavior**
<Just Frozed and appears the Game Exited Screen.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

`No Screenshot by now next comment.`

**Crash Report**
If your game crashed, please paste your crash report below.

```text
No Crash :)
```

**System Information**
 - OS: Android 9
 - Minecraft Version: 1.8.9
 - Forge Version: Latest
 - FDPClient Version: 4.3.0 PREE-2.1

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Optifine

**Additional info**
<BTW fix the Snapdragon CPU Crash on Phones because its crashes from FDP 2.0.2 - Latest,Mediatek was fine on 2.1.2 but less feauture😟😟😟😟.>

Please fix it because i get a news of Matrix Damage Fly and i want to try it 😢😢😢

**Comment by ProSteve12301** [comment]
#30 Like this Problem

**Comment by ProSteve12301** [comment]
Oh i think PojavLauncher Dev was patch this thing so i gonna test it to see if its work.
I wish its patch.

**Comment by ProSteve12301** [comment]
> Oh i think PojavLauncher Dev was patch this thing so i gonna test it to see if its work. I wish its patch.

Ahh not fixed its crashing only.

**Comment by ProSteve12301** [comment]
[**Log of the Game**](https://github.com/UnlegitMC/FDPClient/files/8983483/latestlog.txt)

Linux Support FDPClient has still crashing(even the linux CPU is the same as phone).
BTW so hard to patch and make code on FDP.

**Comment by hackerlod123** [comment]
OS: Android 10
Minecraft Version: 1.8.9
Forge Version: Latest
FDPClient Version: 4.3.0 PREE-2.1

**Comment by ReCaree** [comment]
Optifine can't be installed with FDP Client

**Comment by ProSteve12301** [comment]
All servers are patch everything FDP 2.1.2 isn't bypass BlocksMC,Minebox,JartexandPika Network.Fix it please:)

**Comment by GutatOderSo** [comment]
fdp 2.1.2 is outdated.

**Comment by TheMosKau** [comment]
> Optifine can't be installed with FDP Client

you can lol

**Comment by ReCaree** [comment]
> > Optifine can't be installed with FDP Client
> 
> you can lol

yes sometimes

**Comment by ProSteve12301** [comment]
Anyone can make patch of the support for arm64 cpu and opengles 2-4.Because i a coder but i studiying in computing(school) so can patch this thing so many PojavLauncher players want to hack but only windows only can hack😟😟😟

**Comment by ProSteve12301** [comment]
If this bug cannot fix,im leaving FDPClient and Prioritized to Lime Client that only supports pojavlauncher:( bye thanks for fun but FDP 2.1.2 are no fun at all.
