### ISSUE TITLE
重要的Issue

### ISSUE THREAD

**Issue by ghost** [opZywl/FDPClient-legacy#32]
几个建议给未来的FDPClient
1：添加MusicPlayer（音乐播放器）（**有些录制软件只能录制一个窗口**）
2：去除FDPLoader（**有些人无法访问Github**）
3：添加更多内置字体给Betterfont（比如**Comfortaa，文泉驿微米黑，Roboto**）
4：重新添加Fancy UI（或者HTML UI）
**5：动态模糊！！！！！**

**Comment by HowardZHY** [comment]
你最好把1,3,4,5这些没用的变成一个单独的mod

**Comment by HowardZHY** [comment]
别再拖累client的shitcode了

**Comment by ghost** [comment]
1试过，崩了
3我可以直接替换成Comfortaa，只是不是很兼容
4指的是FDPClient的UI（如果你是指这个那就算了）
5我找不到

**Comment by ghost** [comment]
awa

**Comment by HowardZHY** [comment]
1是liteloader的吗

**Comment by HowardZHY** [comment]
3和4直接导致了很多启动崩溃

**Comment by HowardZHY** [comment]
动态模糊会卡的

**Comment by ghost** [comment]
1是Forge1.8.9Music Player
3试了没事 4可以不整
5我显卡是               （空气）根本不卡
awa

**Comment by HowardZHY** [comment]
没人能保证这些花哨功能不会出问题,最好分出弄一个fancy的版本



在 2022-05-28 19:32:35，"Ds1nk" ***@***.***> 写道：

1是Forge1.8.9Music Player
3试了没事 4可以不整
5我显卡是 （空气）根本不卡
awa

**Comment by choneas** [comment]
如果问题已经解决,请关闭这个Issue。

**Comment by HowardZHY** [comment]
这应该被关闭,这既不重要也不算是真正的问题()



在 2022-05-29 15:30:13，"Chenken520" ***@***.***> 写道：

如果问题已经解决,请关闭这个Issue。

**Comment by HowardZHY** [comment]
close it as useless
