### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by contionability** [opZywl/FDPClient-legacy#36]
@opZywl 
1. I think you'd better learn _**a bit about**_ kotlin before push commits
2. you should learn to read the build-error messages at workflow and fix them
3. you can make multiple files change in Github Desktop App
4. you'd better pause updating before I come back **(June 9th or 10th)**

**Comment by opZywl** [comment]
Okay sorry i pause commits I will do this offline and send only when it is correct

**Comment by opZywl** [comment]
bro @contionability look loader LATEST… have rat LOL

@xiguagege !??
