### ISSUE TITLE
no title

### ISSUE THREAD

**Issue by ll11l1lIllIl1lll** [opZywl/FDPClient-legacy#4]
@contionability 查看一下 Project FDP 群聊或者私信

**Comment by ll11l1lIllIl1lll** [comment]
@contionability 如果你看见了就请delete这个issue <3

**Comment by contionability** [comment]
我在学校
看个锤子

**Comment by contionability** [comment]
你直接在
https://github.com/contionability/contionability/issues
发给我
我在学校看不了

**Comment by contionability** [comment]
不要发图
学校把Github的图禁了
