### ISSUE TITLE
添加PacketFly

### ISSUE THREAD

**Issue by FallenCrystal** [opZywl/FDPClient-legacy#52]
添加PacketFly试图绕过1.9+ NCP服务器
不添加也没关系 只是多一种选择我觉得不是一件坏事 :D
*我希望使用它可以在1.12.2的pvp服务器上飞行 并且没有flag√ 虽然现在tpre飞行能满足需求 但是容易被kick

**Comment by contionability** [comment]
PacketFly需要ConfirmTeleport Packet
1.8.9无法实现（就算带ViaVersion）
