### ISSUE TITLE
Co看qq

### ISSUE THREAD

**Issue by Wlenk** [opZywl/FDPClient-legacy#6]
My account was hacked by Dimples#1337
My account was hacked by Dimples#1337
My account was hacked by Dimples#1337My account was hacked by Dimples#1337

**Comment by Wlenk** [comment]
看qq Co

**Comment by contionability** [comment]
我在学校
:(

**Comment by contionability** [comment]
https://github.com/contionability/contionability/issues
here

**Comment by VeibaeMCC** [comment]
你们在吵什么捏

**Comment by contionability** [comment]
@VeibaeMCC https://github.com/contionability/contionability/issues/2
