### ISSUE TITLE
im new to fdpclient pls help

### ISSUE THREAD

**Issue by tongpay** [opZywl/FDPClient-legacy#7]
1. how do you use vulcan2 when using fly? do you just fly somewhere and press shift? when I tried it it doesn't work.
2. how do u edit the text in spammer module and other modules?

**Comment by BuffOvrFlw** [comment]
first of all , Vulcan fly 2 and legit was patched . 
then use .spammer message < TEXT >

**Comment by tongpay** [comment]
really? i saw someone in a server use vulcan2 and fly to bases tho

**Comment by contionability** [comment]
> first of all , Vulcan fly 2 and legit was patched . then use .spammer message < TEXT >

Patched in Vulcan 2.6.6
Still works on some servers
