### ISSUE TITLE
Not enought information

### ISSUE THREAD

**Issue by SrHallowen** [opZywl/FDPClient-legacy#80]
There is no to litle information on th web of the version the mod for and how to install it i sugere to make an tutorial for it

**Comment by 5rq** [comment]
step 1. learn english
step 2. learn how to use a forge mod?!

**Comment by SrHallowen** [comment]
1. im not english im portuguese so my english is bad
2. i know how to use forge
3. idk the damn version the client is for

**Comment by 5rq** [comment]
3. take a guess

**Comment by 5rq** [comment]
3. 1.8.9
