### ISSUE TITLE
Kill Insults随机字符

### ISSUE THREAD

**Issue by FallenCrystal** [opZywl/FDPClient-legacy#92]
添加随机字符来绕过刷屏检查
如果有 请告诉我怎么做
如果没有 就将其视为新功能请求 thx

**Comment by VeibaeMCC** [comment]
%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s

**Comment by FallenCrystal** [comment]
> %s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s

thx
